# Generated by Django 6.0.3 on 2026-03-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('user_id', models.IntegerField(db_index=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent')], db_index=True, default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Outbox Record',
                'verbose_name_plural': 'Outbox Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='outbox_outb_status_56ae88_idx')],
            },
        ),
    ]
